version: '3'
services:
  yii2:
    build:
      context: 'yii/${BACK_END}'
      dockerfile: 'Dockerfile-${PHP_VERSION}'
      args:
        - 'BACK_END=${BACK_END}'
        - 'USER_ID=${USER_ID}'
        - 'GROUP_ID=${GROUP_ID}'
        - 'PHP_VERSION=${PHP_VERSION}'
        - 'DISPLAY_PHPERROR=${DISPLAY_PHPERROR}'
        - 'XDEBUG=${XDEBUG}'
        - 'INSTALL_ADDITIONAL_EXTENSIONS=${INSTALL_ADDITIONAL_EXTENSIONS}'
    volumes:
      - '${APP_CODE_PATH_HOST}:${APP_CODE_PATH_YII}${APP_CODE_CONTAINER_FLAG}'
    ports:
      - '${YII_HOST_HTTP_PORT}:80'
volumes: {}
