name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Laravel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the image with php 8.1 and nginx
        run: docker-compose -f "docker-compose.yml" up -d --build
        env:
          PHP_VERSION: "8.1"
          BACK_END: nginx
          XDEBUG: true
          DISPLAY_PHPERROR: true
      - name: Build the image with php 8.0 and nginx
        run: docker-compose build
        env:
          PHP_VERSION: "8.0"
          BACK_END: nginx
          XDEBUG: true
          DISPLAY_PHPERROR: true

      - name: Build the image with php 8.1 and apache
        run: docker-compose build
        env:
          PHP_VERSION: "8.1"
          BACK_END: apache
          XDEBUG: true
          DISPLAY_PHPERROR: true
      - name: Build the image with php 8.0 and apache
        run: docker-compose build
        env:
          PHP_VERSION: "8.0"
          BACK_END: apache
          XDEBUG: true
          DISPLAY_PHPERROR: true
